### ISSUE TITLE
[BUG] Missing loot in chests/ Loot tables bugged?

### ISSUE THREAD

**Issue by vydax** [itsdinkd/AQM2#101]
**Modpack Version**
2.0.1

**Minecraft Version**
1.18.1

**Describe the crash or bug**

obsidian heart is not dropping from obsidialith? is something bugged on latest version
also been noticing a lot of chests had no loot in them anymore newly generated chests
its from a ported world from the previous version.

a friends description a bit more accurately
"Went into single player and summoned an obsidialith in the nether, which i was currently in. Killed it and it had normal loot. 
Went onto the server to kill one again. Had an empty chest. Empty meaning, the first click on it didn't open the chest and the 2nd click was an empty one."

no idea what the causes or solutions are but i hope something can be figured out, 

that clicking a chest nothing happening and then clicking it again and u get an empty chest is the weirdest part to me something is going on with the loot tables or them crashing or something.

hopefully it wont be too annoying of a fix, it was fine the previous version so all i can say is check through the things you guys have changed in the latest version. the problem must lie somewhere there.

Good luck on this one. no crash logs or anything available because i cant seem to find anything in console.

**Comment by Ryokushen** [comment]
Also have been privy to the same bug on the multiplayer server I'm on. Same  modpack version and minecraft version. For myself it takes place when opening chests in End Cities consistently and occasionally randomly on chests elsewhere. First click on the chest doesn't register and second click when it opens it's empty.

**Comment by eyesoffaith** [comment]
I've also run into this error. Haven't been able to pinpoint the solution but I believe I caught the error in the log file. I've seen this error message every time we've gone to open a chest and the above situation happened:

`[12:44:22] [Server thread/FATAL] (class_1255) Error executing task on Server
 java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1886.method_8177(net.minecraft.class_1792)" because "enchantment.field_9083" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18) ~[?:?]
        at net.minecraft.item.Item.canApplyAtEnchantingTable(Item:9539) ~[?:?]
        at net.minecraft.enchantment.EnchantmentHelper.handler$goo000$getAvailableEnchantmentResults(EnchantmentHelper:4031) ~[?:?]
        at net.minecraft.enchantment.EnchantmentHelper.getPossibleEntries(EnchantmentHelper) ~[?:?]
        at net.minecraft.enchantment.EnchantmentHelper.generateEnchantments(EnchantmentHelper:360) ~[?:?]
        at net.minecraft.enchantment.EnchantmentHelper.enchant(EnchantmentHelper:318) ~[?:?]
        at net.minecraft.loot.function.EnchantWithLevelsLootFunction.process(EnchantWithLevelsLootFunction:40) ~[?:?]
        at net.minecraft.loot.function.ConditionalLootFunction.apply(ConditionalLootFunction:31) ~[?:?]
        at net.minecraft.loot.function.ConditionalLootFunction.apply(ConditionalLootFunction:20) ~[?:?]
        at net.minecraft.loot.function.LootFunction.method_514(LootFunction:14) ~[?:?]
        at net.minecraft.loot.entry.ItemEntry.generateLoot(ItemEntry:33) ~[?:?]
        at net.minecraft.class_85$1.generateLoot(class_85.java:59) ~[server-intermediary.jar:?]
        at net.minecraft.loot.LootPool.supplyOnce(LootPool:81) ~[?:?]
        at net.minecraft.loot.LootPool.addGeneratedLoot(LootPool:96) ~[?:?]
        at net.minecraft.loot.LootTable.generateUnprocessedLoot(LootTable:73) ~[?:?]
        at net.minecraft.loot.LootTable.generateLoot(LootTable:82) ~[?:?]
        at net.minecraft.loot.LootTable.generateLoot(LootTable:87) ~[?:?]
        at net.minecraft.loot.LootTable.supplyInventory(LootTable:106) ~[?:?]
        at net.minecraft.block.entity.LootableContainerBlockEntity.checkLootInteraction(LootableContainerBlockEntity:82) ~[?:?]
        at net.minecraft.block.entity.LootableContainerBlockEntity.createMenu(LootableContainerBlockEntity:160) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity:1032) ~[?:?]
        at net.minecraft.block.ShulkerBoxBlock.onUse(ShulkerBoxBlock:96) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.redirect$bko000$activateWithOptionalCactus(ServerPlayerInteractionManager:3029) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bhp000$modifiedRunLoop(MinecraftServer:5365) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by eyesoffaith** [comment]
For more context, I have error logs of this happening with 'net.minecraft.block.ShulkerBoxBlock.onUse' (opening Shulker Box) and 'net.minecraft.block.ChestBlock.onUse' (opening Chests). This has been most apparent in The End but also present in freshly loaded chunks in the Overworld as well.

**Comment by vydax** [comment]
yeah i just now noticed that same error
i didnt notice it before. thanks for posting. 
pretty big bug though

**Comment by Archiplex** [comment]
End chests are consistently empty in my multiplayer world after the recent patch, yes.

**Comment by vydax** [comment]
Nether Chests do seem to still spawn loot

**Comment by vydax** [comment]
Any update on this or is it a really bad little bug? Hope its not too difficult to figure out, people on my server have really been getting annoyed since they all love exploring lol. Well anyways good luck on it.

**Comment by eyesoffaith** [comment]
Also hoping for an update on this as my server is very much like vydax's 😂

**Comment by itsdinkd** [comment]
Fixed in 2.0.2
