### ISSUE TITLE
[BUG] Unable to cast Brown Bear to GrizzleyBear

### ISSUE THREAD

**Issue by immeraufdemhund** [itsdinkd/AQM2#47]
**Modpack Version**
1.4.1
**Minecraft Version**
1.18.1
**Describe the bug**

**To Reproduce**
Tried to pull a brown bear with a lead into a fenced area. Then teh server crashed
```
[02:35:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.5) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:883) ~[server-intermediary.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:324) ~[?:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:823) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bfo000$modifiedRunLoop(MinecraftServer:5356) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:663) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.mobz.entity.Brownbear cannot be cast to class com.aqupd.grizzlybear.entities.GrizzlyBearEntity (net.mobz.entity.Brownbear and com.aqupd.grizzlybear.entities.GrizzlyBearEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1e67b872)
        at com.aqupd.grizzlybear.entities.GrizzlyBearEntity$ProtectBabiesGoal.canStart(GrizzlyBearEntity.java:344) ~[grizzlybear-1.18-1.2.1.jar:?]
        at net.minecraft.entity.ai.goal.PrioritizedGoal.canStart(PrioritizedGoal:22) ~[?:?]
        at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:98) ~[?:?]
        at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:737) ~[?:?]
        at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2604) ~[?:?]
        at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:545) ~[?:?]
        at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127) ~[?:?]
        at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:58) ~[?:?]
        at net.minecraft.entity.LivingEntity.tick(LivingEntity:2349) ~[?:?]
        at net.minecraft.entity.mob.MobEntity.tick(MobEntity:345) ~[?:?]
        at com.aqupd.grizzlybear.entities.GrizzlyBearEntity.tick(GrizzlyBearEntity.java:186) ~[grizzlybear-1.18-1.2.1.jar:?]
        at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:699) ~[?:?]
        at net.minecraft.world.World.tickEntity(World:487) ~[?:?]
        at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:360) ~[?:?]
        at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
        at net.minecraft.server.world.ServerWorld.tick(ServerWorld:328) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$bmo000$fixUpdateSuppressionCrashTick(MinecraftServer:6250) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[server-intermediary.jar:?]
        ... 6 more
```

**Expected behavior**

**Screenshots**

**Crash log or latest.log.log**
*Use pastebin.com to generate a link*

**Additional context**

**Comment by itsdinkd** [comment]
Edge case. You more than welcome to report this to the grizzly bear mod devs, otherwise not much I can do.
