### ISSUE TITLE
[BUG] DimensionalDoors

### ISSUE THREAD

**Issue by ZaHecc** [itsdinkd/AQM2#64]
**Modpack Version**
What modpack version
1.3.3

**Minecraft Version**
What mc version
1.18.2

**Describe the crash or bug**
Naturally spawned DimensionalDoors Rifts around the world, when you go through them, they disappear and tell you to create a bug report.

**Steps to reproduce the behavior:**
How can someone replicate this bug/crash?
Try to go through DimensionalDoors Rift

**Expected behavior**
What is the expected outcome?
Deletes the rift and tells you that it wasn't supposed to happen and to report it as a bug

**Screenshots**
Post screenshots if available
[Picture of error message](https://imgur.com/a/ZqbhIeG)

**Crash log or latest.log.log**
use pastebin.com for your log
https://controlc.com/3d6d0cdb
wouldn't let me post to pastebin because it said there was something offensive or something

**Additional context**
Any additional context?
nope

**Comment by alfredtayloraero** [comment]
I've replicated this too! getting the error log now

**Comment by alfredtayloraero** [comment]
``[16:29:03] [Server thread/ERROR]: Teleporting failed with the following exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_14178()" because the return value of "org.dimdev.dimdoors.pockets.PocketGenerationContext.world()" is null
        at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
        at org.dimdev.dimdoors.pockets.virtual.reference.PocketGeneratorReference.prepareAndPlacePocket(PocketGeneratorReference.java:140) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generatePocketV2(PocketGenerator.java:54) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateFromPocketGroupV2(PocketGenerator.java:50) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.pockets.PocketGenerator.generateDungeonPocketV2(PocketGenerator.java:58) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.rift.targets.RandomTarget.receiveOther(RandomTarget.java:159) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.api.rift.target.Target.as(Target.java:16) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.RiftBlockEntity.teleport(RiftBlockEntity.java:194) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.innerTeleport(EntranceRiftBlockEntity.java:81) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.entity.EntranceRiftBlockEntity.teleport(EntranceRiftBlockEntity.java:77) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onCollision(DimensionalDoorBlock.java:121) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at org.dimdev.dimdoors.block.door.DimensionalDoorBlock.onAfterMovePlayerCollision(DimensionalDoorBlock.java:65) ~[DimensionalDoors-4.0.4-1.18.2.jar:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.handler$ebc000$checkBlockCollision(ServerPlayNetworkHandler:10197) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler:955) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:114) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$PositionAndOnGround.apply(PlayerMoveC2SPacket:42) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$ccn000$modifiedRunLoop(MinecraftServer:6405) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]``

**Comment by itsdinkd** [comment]
` they disappear and tell you to create a bug report.`

This means report to the developer, not the modpack. I did not make the mod so i have no control on their own bugs.
